### PR TITLE
Update to use formerr rather then state ErrorMessage

### PR DESCRIPTION
**Pull request by s3than**
Looks to resolve the inability to install plugin in 1.5 [issue 2](https://github.com/coredns/proxy/issues/2)

### CODE REVIEW

**Comment by s3than** [comment]
@miekg Can you confirm that the pull request resolves the install plugin issue

**Comment by s3than** [comment]
@miekg I've found some issues around this and will resolve first

**Comment by xiaohui** [comment]
it works, thx

**Comment by s3than** [comment]
Just for an update
```
How does forward relate to proxy? This plugin is the “new” version of proxy and is faster because it re-uses connections to the upstreams. It also does in-band health checks - using DNS instead of HTTP. Since it is newer it has a little less (production) mileage on it.
```
https://coredns.io/plugins/forward/

**Comment by miekg** [comment]
ah missed this.

**Comment by s3than** [comment]
@miekg Just an FYI I hadn't resolved the tests in https://github.com/coredns/proxy/blob/master/dnstap_test.go Unfortunately just real busy. I'll attempt to look at it shortly

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/proxy] Update to use f..." ]
>@miekg Just an FYI I hadn't resolved the tests in https://github.com/coredns/proxy/blob/master/dnstap_test.go Unfortunately just real busy. I'll attempt to look at it shortly

of course tests! I always forget those as well :-)

**Pull request merged**
